# version: "3.9"
# services:
#   web:
#     build: .
#     restart: unless-stopped
#     ports:
#       - "8080:80"
#   db:
#     image: mariadb:11.3
#     restart: unless-stopped
#     ports:
#       - "3306:3306"
#     environment:
#       MARIADB_DATABASE: immobilier
#       MARIADB_USER: root
#       MARIADB_PASSWORD: root
#       MARIADB_ROOT_PASSWORD: root
#     volumes:
#       - ./data/db:/var/lib/mysql

# version: '3.9'

# services:
#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - 8000:80
#     depends_on:
#       - db
#   db:
#     image: mysql:8.0
#     environment:
#       MYSQL_DATABASE: immobilier
#       MYSQL_PASSWORD: root
#       MYSQL_ROOT_PASSWORD: root
#     volumes:
#       - ./data:/var/lib/mysql

version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    ports:
      - "8000:80"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:$(php artisan key:generate --show)
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=immobilier
      - DB_USERNAME=root
      - DB_PASSWORD=root
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: immobilier
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
